---
mesos_version: "0.20.1"
mesos_file_name: "mesos_{{mesos_version}}-1.0.ubuntu1404_amd64.deb"
mesos_python_file_name: "mesos-{{mesos_version}}-py2.7-linux-x86_64.egg"
mesos_download_url: "http://downloads.mesosphere.io/master/ubuntu/14.04/{{mesos_file_name}}"
mesos_python_download_url: "http://downloads.mesosphere.io/master/ubuntu/14.04/{{mesos_python_file_name}}"

mesos_cluster_name: mesos_cluster
mesos_ip: "{{ansible_eth0.ipv4.address}}"
mesos_log_dir: "/var/log/mesos"
mesos_work_dir: "/var/run/mesos"
mesos_ulimit: "-n 8192"
mesos_zk: "zk://localhost:2181/mesos" # search local by default
mesos_masters: "{{mesos_zk}}" # search local by default
mesos_quorum: 1
