---
- group: name=vnc
- user: name=vnc group=vnc

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Apt install required system packages.
  apt: pkg={{item}} state=installed
  with_items:
    - xfce4
    - tightvncserver
    - expect

- file: path=/home/vnc/.vnc state=directory owner=vnc group=vnc mode=0700

- name: Vnc xstartup config
  template: src=xstartup.j2 dest=/home/vnc/.vnc/xstartup owner=vnc group=vnc mode=0755
  notify: Restart vncserver

- name: Non interactive vncpasswd script
  shell: echo "{{vnc_password}}" | /usr/bin/vncpasswd -f > /home/vnc/.vnc/passwd
  sudo: yes
  sudo_user: vnc

- name: Upstart script
  template: src=vncserver.conf.j2 dest=/etc/init/vncserver.conf
