---
- name: Get Docker release tool key
  apt_key: keyserver={{docker_keyserver}} id={{docker_keyserver_id}} state=present

- name: Add Docker deb repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    state: "present"
    update_cache: yes

- name: Install Docker
  apt:
    name: "{{ docker_version | default('docker-engine') }}"
    state: "present"
