---
- name: Install OpenVPN packages
  apt: pkg={{ item }} state=installed
  with_items:
    - expect
    - openvpn
    - easy-rsa

- name: Add server.conf
  template: src=server.conf.j2 dest=/etc/openvpn/server.conf
  notify: Restart openvpn

- name: Create keys directory
  file: path={{ openvpn_easyrsa_dir }} state=directory

- name: Create index.txt file
  command: touch {{ openvpn_easyrsa_dir }}/index.txt creates={{ openvpn_easyrsa_dir }}/index.txt

- name: Create serial file
  shell: "echo 01 > {{ openvpn_easyrsa_dir }}/serial"
  args:
    creates: "{{ openvpn_easyrsa_dir }}/serial"

- name: Easy rsa vars file
  template: src=easy-rsa-vars.j2 dest=/usr/share/easy-rsa/vars

- name: Add certificate generation scripts
  template: src=generate_ca.sh.j2 dest=/etc/openvpn/generate_ca.sh mode=0755

- name: Add certificate generation scripts
  template: src=generate_crt.sh.j2 dest=/etc/openvpn/generate_crt.sh mode=0755

- name: Run ca script
  command: /etc/openvpn/generate_ca.sh chdir=/usr/share/easy-rsa creates={{ openvpn_easyrsa_dir }}/ca.key
  notify: Restart openvpn

- name: Run crt script
  command: /etc/openvpn/generate_crt.sh chdir=/usr/share/easy-rsa creates={{ openvpn_easyrsa_dir }}/vpn-gateway.key
  notify: Restart openvpn

- name: Diffie something
  shell: ". /usr/share/easy-rsa/vars && cd /usr/share/easy-rsa && /usr/share/easy-rsa/build-dh"
  args:
    creates: "{{ openvpn_easyrsa_dir }}/dh2048.pem"
  notify: Restart openvpn

- name: Allow ipv4 forwarding
  sysctl: name=net.ipv4.ip_forward value=1 state=present

- name: Check if masquerading rule is present in iptables
  shell: iptables -n -t nat -L POSTROUTING
  register: openvpn_iptables_masq
  changed_when: false

- name: Add masq rule to iptables
  command: iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  when: openvpn_iptables_masq.stdout.find("MASQUERADE") == -1

- name: Make sure openvpn is started and enabled
  service: name=openvpn state=started enabled=yes
